import streamlit
#streamlit.title('My Parents New Healthy Diner')
#streamlit.header('Breakfast Menu')
#streamlit.text('Omega 3 & Blueberry Oatmeal')
#streamlit.text('Kale, Spinach & Rocket Smoothie')
#streamlit.text('Hard-Boiled Free-Range Egg')
streamlit.header('Breakfast Favorites')
streamlit.text('🥣 Omega 3 & Blueberry Oatmeal')
streamlit.text('🥗 Kale, Spinach & Rocket Smoothie')
streamit.text('🐔 Hard-Boiled Free-Range Egg')
streamit.text('🥑🍞 Avocado Toast')
streamlit.header('Build Your Own Fruit Smoothie')
